"""Task-store schema initialization and lightweight migrations."""

from __future__ import annotations

from typing import Callable

ConnectionFactory = Callable[[], object]


def _id_column_sql(dialect: str) -> str:
    if dialect == "postgres":
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def ensure_column(
    conn,
    table_name: str,
    existing_columns: set[str],
    column_name: str,
    column_sql: str,
) -> None:
    if column_name in existing_columns:
        return
    if getattr(conn, "dialect", "sqlite") == "postgres":
        conn.execute(f"ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS {column_sql}")  # nosec B608
    else:
        conn.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_sql}")  # nosec B608
    existing_columns.add(column_name)


def _create_web_tasks_table(conn) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS web_tasks (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            task_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            request_id TEXT NOT NULL DEFAULT '-',
            url TEXT NOT NULL,
            schema_name TEXT NOT NULL,
            storage_format TEXT NOT NULL,
            batch_group_id TEXT NOT NULL DEFAULT '',
            task_kind TEXT NOT NULL DEFAULT 'single',
            parent_task_id TEXT NOT NULL DEFAULT '',
            total_items INTEGER NOT NULL DEFAULT 0,
            completed_items INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'pending',
            created_at TEXT NOT NULL,
            completed_at TEXT NOT NULL DEFAULT '',
            elapsed_ms REAL NOT NULL DEFAULT 0,
            quality_score REAL NOT NULL DEFAULT 0,
            progress_percent REAL NOT NULL DEFAULT 0,
            progress_stage TEXT NOT NULL DEFAULT '',
            data_json TEXT NOT NULL DEFAULT '',
            error TEXT NOT NULL DEFAULT ''
        )
        """
    )
    columns = conn.table_columns("web_tasks")
    ensure_column(
        conn,
        "web_tasks",
        columns,
        "tenant_id",
        "tenant_id TEXT NOT NULL DEFAULT 'default'",
    )
    ensure_column(
        conn,
        "web_tasks",
        columns,
        "progress_percent",
        "progress_percent REAL NOT NULL DEFAULT 0",
    )
    ensure_column(
        conn,
        "web_tasks",
        columns,
        "progress_stage",
        "progress_stage TEXT NOT NULL DEFAULT ''",
    )
    ensure_column(
        conn,
        "web_tasks",
        columns,
        "batch_group_id",
        "batch_group_id TEXT NOT NULL DEFAULT ''",
    )
    ensure_column(
        conn,
        "web_tasks",
        columns,
        "task_kind",
        "task_kind TEXT NOT NULL DEFAULT 'single'",
    )
    ensure_column(
        conn,
        "web_tasks",
        columns,
        "parent_task_id",
        "parent_task_id TEXT NOT NULL DEFAULT ''",
    )
    ensure_column(
        conn,
        "web_tasks",
        columns,
        "total_items",
        "total_items INTEGER NOT NULL DEFAULT 0",
    )
    ensure_column(
        conn,
        "web_tasks",
        columns,
        "completed_items",
        "completed_items INTEGER NOT NULL DEFAULT 0",
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_web_tasks_tenant_id ON web_tasks(tenant_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_web_tasks_status ON web_tasks(status)")
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_web_tasks_created_at ON web_tasks(created_at)"
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_web_tasks_url ON web_tasks(url)")
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_web_tasks_batch_group_id ON web_tasks(batch_group_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_web_tasks_parent_task_id ON web_tasks(parent_task_id)"
    )


def _create_templates_table(conn) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS extraction_templates (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            template_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            name TEXT NOT NULL,
            url TEXT NOT NULL DEFAULT '',
            page_type TEXT NOT NULL DEFAULT 'unknown',
            schema_name TEXT NOT NULL DEFAULT 'auto',
            storage_format TEXT NOT NULL DEFAULT 'json',
            use_static INTEGER NOT NULL DEFAULT 0,
            selected_fields_json TEXT NOT NULL DEFAULT '[]',
            field_labels_json TEXT NOT NULL DEFAULT '{{}}',
            profile_json TEXT NOT NULL DEFAULT '{{}}',
            use_count INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_used_at TEXT NOT NULL DEFAULT ''
        )
        """
    )
    columns = conn.table_columns("extraction_templates")
    ensure_column(
        conn,
        "extraction_templates",
        columns,
        "tenant_id",
        "tenant_id TEXT NOT NULL DEFAULT 'default'",
    )
    ensure_column(
        conn,
        "extraction_templates",
        columns,
        "profile_json",
        "profile_json TEXT NOT NULL DEFAULT '{}'",
    )
    ensure_column(
        conn,
        "extraction_templates",
        columns,
        "use_count",
        "use_count INTEGER NOT NULL DEFAULT 0",
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_extraction_templates_tenant_id ON extraction_templates(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_extraction_templates_updated_at ON extraction_templates(updated_at)"
    )


def _create_monitors_table(conn) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS monitor_profiles (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            monitor_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            name TEXT NOT NULL,
            url TEXT NOT NULL,
            schema_name TEXT NOT NULL DEFAULT 'auto',
            storage_format TEXT NOT NULL DEFAULT 'json',
            use_static INTEGER NOT NULL DEFAULT 0,
            selected_fields_json TEXT NOT NULL DEFAULT '[]',
            field_labels_json TEXT NOT NULL DEFAULT '{{}}',
            profile_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_task_id TEXT NOT NULL DEFAULT '',
            last_checked_at TEXT NOT NULL DEFAULT '',
            last_status TEXT NOT NULL DEFAULT '',
            last_alert_level TEXT NOT NULL DEFAULT '',
            last_alert_message TEXT NOT NULL DEFAULT '',
            last_changed_fields_json TEXT NOT NULL DEFAULT '[]',
            last_notification_status TEXT NOT NULL DEFAULT '',
            last_notification_message TEXT NOT NULL DEFAULT '',
            last_notification_at TEXT NOT NULL DEFAULT '',
            last_extraction_strategy TEXT NOT NULL DEFAULT '',
            last_learned_profile_id TEXT NOT NULL DEFAULT '',
            schedule_enabled INTEGER NOT NULL DEFAULT 0,
            schedule_interval_minutes INTEGER NOT NULL DEFAULT 60,
            schedule_next_run_at TEXT NOT NULL DEFAULT '',
            schedule_last_run_at TEXT NOT NULL DEFAULT '',
            schedule_paused_at TEXT NOT NULL DEFAULT '',
            schedule_claimed_by TEXT NOT NULL DEFAULT '',
            schedule_claimed_at TEXT NOT NULL DEFAULT '',
            schedule_lease_until TEXT NOT NULL DEFAULT '',
            schedule_last_error TEXT NOT NULL DEFAULT '',
            schedule_claim_count INTEGER NOT NULL DEFAULT 0,
            last_trigger_source TEXT NOT NULL DEFAULT ''
        )
        """
    )
    columns = conn.table_columns("monitor_profiles")
    for column_name, column_sql in (
        ("tenant_id", "tenant_id TEXT NOT NULL DEFAULT 'default'"),
        ("profile_json", "profile_json TEXT NOT NULL DEFAULT '{}'"),
        (
            "last_notification_status",
            "last_notification_status TEXT NOT NULL DEFAULT ''",
        ),
        (
            "last_notification_message",
            "last_notification_message TEXT NOT NULL DEFAULT ''",
        ),
        ("last_notification_at", "last_notification_at TEXT NOT NULL DEFAULT ''"),
        ("last_extraction_strategy", "last_extraction_strategy TEXT NOT NULL DEFAULT ''"),
        ("last_learned_profile_id", "last_learned_profile_id TEXT NOT NULL DEFAULT ''"),
        ("schedule_enabled", "schedule_enabled INTEGER NOT NULL DEFAULT 0"),
        (
            "schedule_interval_minutes",
            "schedule_interval_minutes INTEGER NOT NULL DEFAULT 60",
        ),
        ("schedule_next_run_at", "schedule_next_run_at TEXT NOT NULL DEFAULT ''"),
        ("schedule_last_run_at", "schedule_last_run_at TEXT NOT NULL DEFAULT ''"),
        ("schedule_paused_at", "schedule_paused_at TEXT NOT NULL DEFAULT ''"),
        ("schedule_claimed_by", "schedule_claimed_by TEXT NOT NULL DEFAULT ''"),
        ("schedule_claimed_at", "schedule_claimed_at TEXT NOT NULL DEFAULT ''"),
        ("schedule_lease_until", "schedule_lease_until TEXT NOT NULL DEFAULT ''"),
        ("schedule_last_error", "schedule_last_error TEXT NOT NULL DEFAULT ''"),
        ("schedule_claim_count", "schedule_claim_count INTEGER NOT NULL DEFAULT 0"),
        ("last_trigger_source", "last_trigger_source TEXT NOT NULL DEFAULT ''"),
    ):
        ensure_column(conn, "monitor_profiles", columns, column_name, column_sql)
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_monitor_profiles_tenant_id ON monitor_profiles(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_monitor_profiles_updated_at ON monitor_profiles(updated_at)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_monitor_profiles_schedule_next_run_at ON monitor_profiles(schedule_next_run_at)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_monitor_profiles_schedule_lease_until ON monitor_profiles(schedule_lease_until)"
    )


def _create_queue_table(conn) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS web_task_dispatch_queue (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            tenant_id TEXT NOT NULL DEFAULT 'default',
            task_id TEXT NOT NULL UNIQUE,
            backend TEXT NOT NULL DEFAULT 'sqlite',
            queue_scope TEXT NOT NULL DEFAULT '*',
            payload_json TEXT NOT NULL DEFAULT '{{}}',
            status TEXT NOT NULL DEFAULT 'queued',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            claimed_at TEXT NOT NULL DEFAULT '',
            worker_id TEXT NOT NULL DEFAULT '',
            last_error TEXT NOT NULL DEFAULT ''
        )
        """
    )
    columns = conn.table_columns("web_task_dispatch_queue")
    ensure_column(
        conn,
        "web_task_dispatch_queue",
        columns,
        "tenant_id",
        "tenant_id TEXT NOT NULL DEFAULT 'default'",
    )
    ensure_column(
        conn,
        "web_task_dispatch_queue",
        columns,
        "backend",
        "backend TEXT NOT NULL DEFAULT 'sqlite'",
    )
    ensure_column(
        conn,
        "web_task_dispatch_queue",
        columns,
        "queue_scope",
        "queue_scope TEXT NOT NULL DEFAULT '*'",
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_web_task_dispatch_queue_tenant_id ON web_task_dispatch_queue(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_web_task_dispatch_queue_status ON web_task_dispatch_queue(status)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_web_task_dispatch_queue_updated_at ON web_task_dispatch_queue(updated_at)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_web_task_dispatch_queue_backend_scope ON web_task_dispatch_queue(backend, queue_scope, status)"
    )


def _create_notification_events_table(conn) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS monitor_notification_events (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            notification_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            monitor_id TEXT NOT NULL DEFAULT '',
            task_id TEXT NOT NULL DEFAULT '',
            channel_type TEXT NOT NULL DEFAULT 'webhook',
            target TEXT NOT NULL DEFAULT '',
            event_type TEXT NOT NULL DEFAULT 'monitor_alert',
            status TEXT NOT NULL DEFAULT 'pending',
            status_message TEXT NOT NULL DEFAULT '',
            attempt_no INTEGER NOT NULL DEFAULT 1,
            max_attempts INTEGER NOT NULL DEFAULT 3,
            next_retry_at TEXT NOT NULL DEFAULT '',
            response_code INTEGER,
            error_type TEXT NOT NULL DEFAULT '',
            error_message TEXT NOT NULL DEFAULT '',
            payload_snapshot_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL,
            sent_at TEXT NOT NULL DEFAULT '',
            retry_of_notification_id TEXT NOT NULL DEFAULT '',
            triggered_by TEXT NOT NULL DEFAULT 'system'
        )
        """
    )
    columns = conn.table_columns("monitor_notification_events")
    for column_name, column_sql in (
        ("tenant_id", "tenant_id TEXT NOT NULL DEFAULT 'default'"),
        ("status_message", "status_message TEXT NOT NULL DEFAULT ''"),
        (
            "retry_of_notification_id",
            "retry_of_notification_id TEXT NOT NULL DEFAULT ''",
        ),
        ("triggered_by", "triggered_by TEXT NOT NULL DEFAULT 'system'"),
    ):
        ensure_column(
            conn,
            "monitor_notification_events",
            columns,
            column_name,
            column_sql,
        )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_monitor_notification_events_tenant_id ON monitor_notification_events(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_monitor_notification_events_monitor_id ON monitor_notification_events(monitor_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_monitor_notification_events_task_id ON monitor_notification_events(task_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_monitor_notification_events_status ON monitor_notification_events(status)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_monitor_notification_events_created_at ON monitor_notification_events(created_at)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_monitor_notification_events_retry_of_notification_id ON monitor_notification_events(retry_of_notification_id)"
    )


def _create_auth_tables(conn) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS web_users (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            user_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            username TEXT NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'viewer',
            display_name TEXT NOT NULL DEFAULT '',
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_login_at TEXT NOT NULL DEFAULT ''
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_web_users_tenant_id ON web_users(tenant_id)"
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_web_users_tenant_username ON web_users(tenant_id, username)"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS web_sessions (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            session_id TEXT NOT NULL UNIQUE,
            user_id TEXT NOT NULL,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            issued_at TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            revoked_at TEXT NOT NULL DEFAULT '',
            last_seen_at TEXT NOT NULL DEFAULT ''
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_web_sessions_user_id ON web_sessions(user_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_web_sessions_tenant_id ON web_sessions(tenant_id)"
    )


def _create_audit_tables(conn) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS audit_logs (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            audit_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            actor_user_id TEXT NOT NULL DEFAULT '',
            actor_role TEXT NOT NULL DEFAULT '',
            action TEXT NOT NULL,
            resource_type TEXT NOT NULL DEFAULT '',
            resource_id TEXT NOT NULL DEFAULT '',
            request_id TEXT NOT NULL DEFAULT '-',
            http_method TEXT NOT NULL DEFAULT '',
            path TEXT NOT NULL DEFAULT '',
            remote_addr TEXT NOT NULL DEFAULT '',
            auth_mode TEXT NOT NULL DEFAULT '',
            payload_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant_id ON audit_logs(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_user_id ON audit_logs(actor_user_id)"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS task_reviews (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            review_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            task_id TEXT NOT NULL,
            reviewer_user_id TEXT NOT NULL DEFAULT '',
            confirmed INTEGER NOT NULL DEFAULT 0,
            accuracy_score REAL NOT NULL DEFAULT 0,
            notes TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_task_reviews_tenant_id ON task_reviews(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_task_reviews_task_id ON task_reviews(task_id)"
    )


def _create_actor_tables(conn) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS installed_actor_packages (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            actor_instance_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            actor_id TEXT NOT NULL,
            name TEXT NOT NULL DEFAULT '',
            version TEXT NOT NULL DEFAULT '',
            category TEXT NOT NULL DEFAULT '',
            capabilities_json TEXT NOT NULL DEFAULT '[]',
            config_json TEXT NOT NULL DEFAULT '{{}}',
            linked_template_id TEXT NOT NULL DEFAULT '',
            linked_monitor_id TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'active',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_run_at TEXT NOT NULL DEFAULT ''
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_installed_actor_packages_tenant_id ON installed_actor_packages(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_installed_actor_packages_actor_id ON installed_actor_packages(actor_id)"
    )


def _create_runtime_ops_tables(conn) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS worker_nodes (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            worker_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            display_name TEXT NOT NULL DEFAULT '',
            node_type TEXT NOT NULL DEFAULT 'worker',
            status TEXT NOT NULL DEFAULT 'idle',
            queue_scope TEXT NOT NULL DEFAULT '*',
            current_load INTEGER NOT NULL DEFAULT 0,
            capabilities_json TEXT NOT NULL DEFAULT '[]',
            metadata_json TEXT NOT NULL DEFAULT '{{}}',
            last_seen_at TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_error TEXT NOT NULL DEFAULT ''
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_worker_nodes_tenant_id ON worker_nodes(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_worker_nodes_status ON worker_nodes(status)"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS proxy_pool_endpoints (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            proxy_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            name TEXT NOT NULL DEFAULT '',
            proxy_url TEXT NOT NULL DEFAULT '',
            provider TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'idle',
            enabled INTEGER NOT NULL DEFAULT 1,
            tags_json TEXT NOT NULL DEFAULT '[]',
            metadata_json TEXT NOT NULL DEFAULT '{{}}',
            success_count INTEGER NOT NULL DEFAULT 0,
            failure_count INTEGER NOT NULL DEFAULT 0,
            last_used_at TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_error TEXT NOT NULL DEFAULT ''
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_proxy_pool_endpoints_tenant_id ON proxy_pool_endpoints(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_proxy_pool_endpoints_enabled ON proxy_pool_endpoints(enabled)"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS site_execution_policies (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            policy_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            domain TEXT NOT NULL,
            name TEXT NOT NULL DEFAULT '',
            min_interval_seconds REAL NOT NULL DEFAULT 0,
            max_concurrency INTEGER NOT NULL DEFAULT 1,
            use_proxy_pool INTEGER NOT NULL DEFAULT 0,
            preferred_proxy_tags_json TEXT NOT NULL DEFAULT '[]',
            assigned_worker_group TEXT NOT NULL DEFAULT '',
            notes TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_site_execution_policies_tenant_domain ON site_execution_policies(tenant_id, domain)"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS site_execution_runtime (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            tenant_id TEXT NOT NULL DEFAULT 'default',
            domain TEXT NOT NULL,
            active_count INTEGER NOT NULL DEFAULT 0,
            next_allowed_at TEXT NOT NULL DEFAULT '',
            last_started_at TEXT NOT NULL DEFAULT '',
            last_finished_at TEXT NOT NULL DEFAULT '',
            updated_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_site_execution_runtime_tenant_domain ON site_execution_runtime(tenant_id, domain)"
    )


def _create_annotation_tables(conn) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS task_annotations (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            annotation_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            task_id TEXT NOT NULL,
            profile_id TEXT NOT NULL DEFAULT '',
            template_id TEXT NOT NULL DEFAULT '',
            corrected_data_json TEXT NOT NULL DEFAULT '{{}}',
            field_feedback_json TEXT NOT NULL DEFAULT '{{}}',
            notes TEXT NOT NULL DEFAULT '',
            created_by TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_task_annotations_tenant_id ON task_annotations(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_task_annotations_task_id ON task_annotations(task_id)"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS template_repair_suggestions (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            repair_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            annotation_id TEXT NOT NULL DEFAULT '',
            task_id TEXT NOT NULL DEFAULT '',
            profile_id TEXT NOT NULL DEFAULT '',
            template_id TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'suggested',
            repair_strategy TEXT NOT NULL DEFAULT 'manual_feedback',
            suggested_fields_json TEXT NOT NULL DEFAULT '[]',
            suggested_field_labels_json TEXT NOT NULL DEFAULT '{{}}',
            suggested_profile_json TEXT NOT NULL DEFAULT '{{}}',
            reason TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            applied_at TEXT NOT NULL DEFAULT ''
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_template_repair_suggestions_tenant_id ON template_repair_suggestions(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_template_repair_suggestions_task_id ON template_repair_suggestions(task_id)"
    )


def _create_funnel_tables(conn) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS growth_funnel_events (
            id {_id_column_sql(getattr(conn, "dialect", "sqlite"))},
            funnel_event_id TEXT NOT NULL UNIQUE,
            tenant_id TEXT NOT NULL DEFAULT 'default',
            stage TEXT NOT NULL DEFAULT '',
            channel TEXT NOT NULL DEFAULT '',
            package_type TEXT NOT NULL DEFAULT '',
            package_id TEXT NOT NULL DEFAULT '',
            package_name TEXT NOT NULL DEFAULT '',
            task_id TEXT NOT NULL DEFAULT '',
            template_id TEXT NOT NULL DEFAULT '',
            monitor_id TEXT NOT NULL DEFAULT '',
            actor_instance_id TEXT NOT NULL DEFAULT '',
            metadata_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_growth_funnel_events_tenant_id ON growth_funnel_events(tenant_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_growth_funnel_events_stage ON growth_funnel_events(stage)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_growth_funnel_events_package_id ON growth_funnel_events(package_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_growth_funnel_events_created_at ON growth_funnel_events(created_at)"
    )


def initialize_task_store_schema(*, connect: ConnectionFactory) -> None:
    with connect() as conn:
        _create_web_tasks_table(conn)
        _create_templates_table(conn)
        _create_monitors_table(conn)
        _create_queue_table(conn)
        _create_notification_events_table(conn)
        _create_auth_tables(conn)
        _create_audit_tables(conn)
        _create_actor_tables(conn)
        _create_runtime_ops_tables(conn)
        _create_annotation_tables(conn)
        _create_funnel_tables(conn)
        conn.commit()
